// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://scrnefzlozfshqwbjvst.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNjcm5lZnpsb3pmc2hxd2JqdnN0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg5OTA1NjAsImV4cCI6MjA1NDU2NjU2MH0.NFk-ZLLYu_fGfAdHGVJVRKVasRjj88XrUzuBif8VV-U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);